on:
  push:
    branches:
      - 'actions-next'

name: Build All MAGE Server Packages

env:
  MAGE_SHOULD_TEST: ${{ !contains(github.ref, 'next') }}

jobs:
  build_service:
    name: Build MAGE Service
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 12, 14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: install native dev libs
        run: |
          sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: |
            service/package-lock.json
            plugins/nga-msi/package-lock.json
      - name: build service
        run: |
          cd service
          npm ci
          npm run build
      - name: test service
        if: ${{ fromJSON(env.MAGE_SHOULD_TEST) }}
        run: npm run --prefix service ci:test
      - name: pack service
        run: npm pack ./service
      - name: build plugin nga-msi
        run: |
          cd plugins/nga-msi
          npm ci
          npm run build
      - name: test plugin nga-msi
        if: ${{ fromJSON(env.MAGE_SHOULD_TEST) }}
        run: npm run --prefix plugins/nga-msi test:run
      - name: pack nga-msi
        run: npm pack ./plugins/nga-msi
      - name: upload packages
        uses: actions/upload-artifact@v2
        with:
          name: mage_service_packages-node-${{ matrix.node }}
          path: |
            ngageoint-mage.*.tgz
  build_web-app:
    name: Build MAGE Web App
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm
          cache-dependency-path: web-app/package-lock.json
      - name: build web-app
        run: |
          cd web-app
          npm ci
          npm run build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
      - name: test web-app
        if: ${{ fromJSON(env.MAGE_SHOULD_TEST) }}
        run: npm run --prefix web-app test-headless
      - name: pack web-app
        run: npm pack ./web-app/dist/app
      - name: upload packages
        uses: actions/upload-artifact@v2
        with:
          name: mage_web-app_packages
          path: |
            ngageoint-mage.*.tgz
  build_instance:
    needs: [ build_service, build_web-app ]
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 12, 14 ]
    runs-on: ${{ matrix.os }}
    steps:
      # - name: checkout
      #   uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: install json utility
        run: npm i json
      - name: download service artifacts
        uses: actions/download-artifact@v2
        with:
          name: mage_service_packages-node-${{ matrix.node }}
      - name: download web-app artifacts
        uses: actions/download-artifact@v2
        with:
          name: mage_web-app_packages
      - name: list artifacts
        run: ls -R
      - name: create package.json
        run: |
          (printf '{ "name": "mage-instance", "version": "%s" }' ${{ github.ref_name }})
          (printf '{ "dependencies": {"@ngageoint/mage.service":"./%s" }}\n' $(ls -1 *mage.service*.tgz)) &&
          (printf '{ "dependencies": {"@ngageoint/mage.web-app":"./%s" }}\n' $(ls -1 *mage.web-app*.tgz)) &&
          (printf '{ "dependencies": {"@ngageoint/nga-msi":"%s" }}\n' $(ls -1 *mage.nga-msi*.tgz) |
          npx json --deep-merge > package.json
      - name: upload package.json
        uses: actions/upload-artifact@v2
        with:
          name: mage_instance_package-node-${{ matrix.node }}
          path: package.json


